[pytest]
pythonpath = .
testpaths = tests
addopts = -q
filterwarnings =
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
    ignore:Setting per-request cookies:DeprecationWarning
